/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication7;
import java.sql.*;

/**
 *
 * @author vishn
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
{
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        da = new javax.swing.JTextField();
        ti = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        co = new javax.swing.JTextField();
        no = new javax.swing.JTextField();
        st = new javax.swing.JTextField();
        ow = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fi1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("                  CURRENT RIDE DETAILS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 241, -1));

        jLabel5.setText("           DATE                                        TIME                                       COST");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 385, -1));

        mo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moActionPerformed(evt);
            }
        });
        getContentPane().add(mo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 108, 35));

        jLabel4.setText("      OWNER ID                           OWNER MOBILE                      CAR NUMBER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 385, -1));
        getContentPane().add(ca, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 102, 35));

        jLabel7.setText("    STARTING POINT");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 108, -1));
        getContentPane().add(da, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 105, 41));

        ti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiActionPerformed(evt);
            }
        });
        getContentPane().add(ti, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 108, 41));

        jLabel8.setText("FINISHING POINT                     NO. OF SEATS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 230, -1));

        co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coActionPerformed(evt);
            }
        });
        getContentPane().add(co, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 102, 41));
        getContentPane().add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 108, 41));
        getContentPane().add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 108, 41));
        getContentPane().add(ow, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 105, 35));

        jLabel1.setText("YOU CAN GO FOR ANOTHER RIDE ONLY AFTER YOUR CURRENT RIDE IS COMPLETED");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 421, 29));

        jLabel2.setText("THANK YOU FOR USING OUR SERVICES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 233, 50));

        jButton1.setText("view");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));
        getContentPane().add(fi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 108, 41));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiActionPerformed

    private void coActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try{
        Class.forName("oracle.jdbc.driver.OracleDriver");
        String server="localhost";
        String portnumber="1521";
        String sid="xe";
        String url="jdbc:oracle:thin:@"+server+":"+portnumber+":"+sid;
        Connection con;
        PreparedStatement pr;
        con=DriverManager.getConnection(url,"system","9961");
        String s=st.getText();
        String p=no.getText();
        pr=con.prepareStatement("select * from ride where start1=? and finish=? and usn not in(select osn from pool)");
        pr.setString(1,s);
        pr.setString(2,p);
        ResultSet rs=pr.executeQuery();
        while(rs.next())
        {
            da.setText(rs.getString("day"));
            ti.setText(rs.getString("time"));
            co.setText(Integer.toString(rs.getInt("cost")));
            no.setText(Integer.toString(rs.getInt("no")));
            Statement st=con.createStatement();
            String u=rs.getString("usn");
        ResultSet rq=st.executeQuery("select * from owner where usn='"+u+"'");
        while(rq.next())
                {
                    ow.setText(rq.getString("name"));
                    ca.setText(rq.getString("car"));
                    mo.setText(Integer.toString(rq.getInt("no")));
                }
        }con.close();
    }  
         catch(ClassNotFoundException e){
        System.out.println(e+"3");
    }
    catch(SQLException e){
    System.out.println(e+"4");
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void moActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        
    }  
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ca;
    private javax.swing.JTextField co;
    private javax.swing.JTextField da;
    private javax.swing.JTextField fi1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField mo;
    private javax.swing.JTextField no;
    private javax.swing.JTextField ow;
    private javax.swing.JTextField st;
    private javax.swing.JTextField ti;
    // End of variables declaration//GEN-END:variables
}
