/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication7;

import javax.swing.JList;

/**
 *
 * @author vishn
 */
import java.sql.*;
public class owner extends javax.swing.JFrame {
Connection con;
PreparedStatement pr;
static String usn;
static String pw;
String start;
String finish;
String time;
String day;
String pa[]=new String[5];
int cost,nos;
ResultSet rs;
    

    /**
     * Creates new form owner
     */
    public owner() {
        initComponents();
    }
void connect() {
        //To change body of generated methods, choose Tools | Templates.
        try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        String server="localhost";
        String portnumber="1521";
        String sid="xe";
        String url="jdbc:oracle:thin:@"+server+":"+portnumber+":"+sid;
        con=DriverManager.getConnection(url,"system","9961");
        pr=con.prepareStatement("select * from ride where usn=?");
        pr.setString(1,usn);
        rs=pr.executeQuery();
        String z="";
       while(rs.next())
        {
            da1.setText(rs.getString("day"));
            ti1.setText(rs.getString("time"));
            int a=rs.getInt("no");
            no1.setText(Integer.toString(a));
            co1.setText(Integer.toString(rs.getInt("cost")));
            st1.setText(rs.getString("start1"));
            fi1.setText(rs.getString("finish"));
        }
        Statement st=con.createStatement();
        ResultSet rq=st.executeQuery("select * from user1 where usn in(select usn from pool where osn='"+usn+"')");
        while(rq.next())
                {
                    pa5.setText(rq.getString("name"));
                    pa1.setText(rq.getString("no"));
                    jTextField1.setText(rq.getString("addr"));
                }
        
        con.close();
    }                                        
    catch(ClassNotFoundException e){
        System.out.println(e);
    }
    catch(SQLException e){
    System.out.println(e);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        st = new javax.swing.JTextField();
        fi = new javax.swing.JTextField();
        ti = new javax.swing.JTextField();
        da = new javax.swing.JTextField();
        da1 = new javax.swing.JTextField();
        st1 = new javax.swing.JTextField();
        fi1 = new javax.swing.JTextField();
        ti1 = new javax.swing.JTextField();
        co1 = new javax.swing.JTextField();
        co = new javax.swing.JTextField();
        no1 = new javax.swing.JTextField();
        max = new javax.swing.JTextField();
        pa1 = new javax.swing.JTextField();
        pa5 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 204));
        jButton1.setText("NEW RIDE");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 231, 32));

        st.setBackground(new java.awt.Color(3, 0, 0));
        st.setForeground(new java.awt.Color(130, 198, 242));
        st.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 142, 36));

        fi.setBackground(new java.awt.Color(3, 0, 0));
        fi.setForeground(new java.awt.Color(130, 198, 242));
        fi.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(fi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 170, 34));

        ti.setBackground(new java.awt.Color(3, 0, 0));
        ti.setForeground(new java.awt.Color(130, 198, 242));
        ti.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        ti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiActionPerformed(evt);
            }
        });
        getContentPane().add(ti, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 170, 33));

        da.setBackground(new java.awt.Color(3, 0, 0));
        da.setForeground(new java.awt.Color(130, 198, 242));
        da.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        da.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daActionPerformed(evt);
            }
        });
        getContentPane().add(da, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 140, 32));

        da1.setEditable(false);
        da1.setBackground(new java.awt.Color(3, 0, 0));
        da1.setForeground(new java.awt.Color(130, 198, 242));
        da1.setText("   NO DATA");
        da1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(da1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 68, 30));

        st1.setEditable(false);
        st1.setBackground(new java.awt.Color(3, 0, 0));
        st1.setForeground(new java.awt.Color(130, 198, 242));
        st1.setText("      NO DATA");
        st1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(st1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 350, 100, 30));

        fi1.setEditable(false);
        fi1.setBackground(new java.awt.Color(3, 0, 0));
        fi1.setForeground(new java.awt.Color(130, 198, 242));
        fi1.setText("       NO DATA");
        fi1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(fi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 110, 30));

        ti1.setEditable(false);
        ti1.setBackground(new java.awt.Color(3, 0, 0));
        ti1.setForeground(new java.awt.Color(130, 198, 242));
        ti1.setText("  NO DATA");
        ti1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        ti1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ti1ActionPerformed(evt);
            }
        });
        getContentPane().add(ti1, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 350, 60, 30));

        co1.setEditable(false);
        co1.setBackground(new java.awt.Color(3, 0, 0));
        co1.setForeground(new java.awt.Color(130, 198, 242));
        co1.setText("    NO DATA");
        co1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        co1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                co1ActionPerformed(evt);
            }
        });
        getContentPane().add(co1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 100, 30));

        co.setBackground(new java.awt.Color(3, 0, 0));
        co.setForeground(new java.awt.Color(130, 198, 242));
        co.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(co, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 140, 32));

        no1.setEditable(false);
        no1.setBackground(new java.awt.Color(3, 0, 0));
        no1.setForeground(new java.awt.Color(130, 198, 242));
        no1.setText("        NO DATA");
        no1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        no1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no1ActionPerformed(evt);
            }
        });
        getContentPane().add(no1, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 350, 110, 30));

        max.setBackground(new java.awt.Color(3, 0, 0));
        max.setForeground(new java.awt.Color(130, 198, 242));
        max.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxActionPerformed(evt);
            }
        });
        getContentPane().add(max, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 170, 32));

        pa1.setEditable(false);
        pa1.setBackground(new java.awt.Color(3, 0, 0));
        pa1.setForeground(new java.awt.Color(130, 198, 242));
        pa1.setText("       NO DATA");
        pa1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(pa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 120, 30));

        pa5.setEditable(false);
        pa5.setBackground(new java.awt.Color(3, 0, 0));
        pa5.setForeground(new java.awt.Color(130, 198, 242));
        pa5.setText("      NO DATA");
        pa5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(pa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 120, 30));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(3, 0, 0));
        jTextField1.setForeground(new java.awt.Color(130, 198, 242));
        jTextField1.setText("      NO DATA");
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 250, 30));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 204));
        jButton2.setText("VIEW CURRENT RIDE DETAILS");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 230, 30));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(96, 200, 227));
        jLabel1.setText("DATE          STARTING POINT           FINISH POINT           TIME          COST PER HEAD            NO OF SEATS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 580, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(62, 177, 227));
        jLabel2.setText(" A CAR OWNER CAN HANDLE ONLY ONE RIDE AT A TIME SO START NEW RIDE ONLY AFTER COMPLETING CURRENT RIDE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 640, 26));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(96, 200, 227));
        jLabel4.setText("     PASSENGER NAME             MOBILE NUMBER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 308, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(96, 200, 227));
        jLabel5.setText("ADDRESS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 130, 30));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(49, 216, 180));
        jLabel6.setText("                    DATE    :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 130, 30));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(49, 216, 180));
        jLabel7.setText("                    COST    :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 130, 30));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(49, 216, 180));
        jLabel8.setText(":   FINISHING POINT");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 140, 30));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(49, 216, 180));
        jLabel9.setText(":  TIME");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 130, 30));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(49, 216, 180));
        jLabel10.setText(":  NO OF SEATS");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 130, 30));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(49, 216, 180));
        jLabel11.setText("      STARTING POINT    :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 130, 30));

        jLabel3.setBackground(new java.awt.Color(7, 7, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/Black bull.jpg"))); // NOI18N
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
             Class.forName("oracle.jdbc.driver.OracleDriver");
        String server="localhost";
        String portnumber="1521";
        String sid="xe";
        String url="jdbc:oracle:thin:@"+server+":"+portnumber+":"+sid;
        con=DriverManager.getConnection(url,"system","9961");
        pr=con.prepareStatement("delete from ride where usn=?");
pr.setString(1,usn);
pr.executeUpdate();
pr=con.prepareStatement("delete from pool where osn=?");
pr.setString(1,usn);
pr.executeUpdate();
start=st.getText();
finish=fi.getText();
time=ti.getText();
day=da.getText();
cost=Integer.parseInt(co.getText());
nos=Integer.parseInt(max.getText());
pr=con.prepareStatement("insert into ride values(?,?,?,?,?,?,?)");
pr.setString(1,usn);
pr.setString(2,start);
pr.setString(3,finish);
pr.setString(4,time);
pr.setString(5,day);
pr.setInt(6,cost);
pr.setInt(7,nos);
pr.executeUpdate();

   pr=con.prepareStatement("select * from ride where usn=?");
   System.out.println(usn);
        pr.setString(1,usn);
        rs=pr.executeQuery();
        String z="";
        while(rs.next())
        {
            da1.setText(rs.getString("day"));
            ti1.setText(rs.getString("time"));
            int a=rs.getInt("no");
            no1.setText(Integer.toString(a));
            co1.setText(rs.getString("cost"));
            st1.setText(rs.getString("start1"));
            fi1.setText(rs.getString("finish"));
        }
        
                    pa5.setText("NO DATA");
                    pa1.setText("NO DATA");
                    jTextField1.setText("NO DATA");
                con.close();
        }
        catch(ClassNotFoundException e){
            System.out.println(e);
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void daActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daActionPerformed

    private void tiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiActionPerformed

    private void co1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_co1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_co1ActionPerformed

    private void no1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        connect();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ti1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ti1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ti1ActionPerformed

    private void maxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        usn=args[0];
        pw=args[1];
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new owner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField co;
    private javax.swing.JTextField co1;
    private javax.swing.JTextField da;
    private javax.swing.JTextField da1;
    private javax.swing.JTextField fi;
    private javax.swing.JTextField fi1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField max;
    private javax.swing.JTextField no1;
    private javax.swing.JTextField pa1;
    private javax.swing.JTextField pa5;
    private javax.swing.JTextField st;
    private javax.swing.JTextField st1;
    private javax.swing.JTextField ti;
    private javax.swing.JTextField ti1;
    // End of variables declaration//GEN-END:variables
}
