/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication7;

/**
 *
 * @author vishn
 */
import java.sql.*;
public class rideuser extends javax.swing.JFrame {

    /**
     * Creates new form rideuser
     */
    public rideuser() {
        initComponents();
    }
static String usn;
void connect()
{
     try{
        Class.forName("oracle.jdbc.driver.OracleDriver");
        String server="localhost";
        String portnumber="1521";
        String sid="xe";
        String url="jdbc:oracle:thin:@"+server+":"+portnumber+":"+sid;
        Connection con;
        PreparedStatement pr;
        con=DriverManager.getConnection(url,"system","9961");
        pr=con.prepareStatement("select * from ride where usn=?");
        pr.setString(1,usn);
        ResultSet rs=pr.executeQuery();
        while(rs.next())
        {
            da.setText(rs.getString("day"));
            ti.setText(rs.getString("time"));
            co.setText(Integer.toString(rs.getInt("cost")));
            no.setText(Integer.toString(rs.getInt("no")));
            st1.setText(rs.getString("start1"));
            fi1.setText("finish");
            Statement st=con.createStatement();
            String u=rs.getString("usn");
        ResultSet rq=st.executeQuery("select * from owner where usn='"+u+"'");
        while(rq.next())
                {
                    ow.setText(rq.getString("name"));
                    ca.setText(rq.getString("car"));
                    mo.setText(Integer.toString(rq.getInt("no")));
                }
        }con.close();
    }  
         catch(ClassNotFoundException e){
        System.out.println(e+"3");
    }
    catch(SQLException e){
    System.out.println(e+"4");
    }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        da = new javax.swing.JTextField();
        ti = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        co = new javax.swing.JTextField();
        no = new javax.swing.JTextField();
        st1 = new javax.swing.JTextField();
        ow = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fi1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(54, 169, 185));
        jLabel3.setText("  CURRENT RIDE DETAILS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 130, 20));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(54, 169, 185));
        jLabel5.setText("       DATE                                      TIME                                     COST");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 410, -1));

        mo.setBackground(new java.awt.Color(0, 0, 0));
        mo.setForeground(new java.awt.Color(0, 204, 204));
        mo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        mo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moActionPerformed(evt);
            }
        });
        getContentPane().add(mo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 200, 35));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(54, 169, 185));
        jLabel4.setText("      OWNER ID                                  OWNER MOBILE                                       CAR NUMBER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 560, -1));

        ca.setBackground(new java.awt.Color(0, 0, 0));
        ca.setForeground(new java.awt.Color(0, 204, 204));
        ca.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(ca, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 190, 35));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(54, 169, 185));
        jLabel7.setText("    STARTING POINT");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 120, 20));

        da.setBackground(new java.awt.Color(0, 0, 0));
        da.setForeground(new java.awt.Color(0, 204, 204));
        da.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(da, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 105, 41));

        ti.setBackground(new java.awt.Color(0, 0, 0));
        ti.setForeground(new java.awt.Color(0, 204, 204));
        ti.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        ti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiActionPerformed(evt);
            }
        });
        getContentPane().add(ti, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 108, 41));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(54, 169, 185));
        jLabel8.setText("FINISHING POINT                                   NO. OF SEATS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 330, 20));

        co.setBackground(new java.awt.Color(0, 0, 0));
        co.setForeground(new java.awt.Color(0, 204, 204));
        co.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coActionPerformed(evt);
            }
        });
        getContentPane().add(co, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 102, 41));

        no.setBackground(new java.awt.Color(0, 0, 0));
        no.setForeground(new java.awt.Color(0, 204, 204));
        no.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        getContentPane().add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 170, 41));

        st1.setBackground(new java.awt.Color(0, 0, 0));
        st1.setForeground(new java.awt.Color(0, 204, 204));
        st1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(st1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 160, 41));

        ow.setBackground(new java.awt.Color(0, 0, 0));
        ow.setForeground(new java.awt.Color(0, 204, 204));
        ow.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(ow, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 150, 35));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(54, 169, 185));
        jLabel1.setText("YOU CAN GO FOR ANOTHER RIDE ONLY AFTER YOUR CURRENT RIDE IS COMPLETED");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 550, 40));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(54, 169, 185));
        jButton1.setText("view");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, 20));

        fi1.setBackground(new java.awt.Color(0, 0, 0));
        fi1.setForeground(new java.awt.Color(0, 204, 204));
        fi1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(fi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 210, 41));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/black-car-wallpapers-for-desktop-20-background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moActionPerformed

    private void tiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiActionPerformed

    private void coActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        connect();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rideuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rideuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rideuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rideuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        usn=args[0];
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rideuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ca;
    private javax.swing.JTextField co;
    private javax.swing.JTextField da;
    private javax.swing.JTextField fi1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField mo;
    private javax.swing.JTextField no;
    private javax.swing.JTextField ow;
    private javax.swing.JTextField st1;
    private javax.swing.JTextField ti;
    // End of variables declaration//GEN-END:variables
}
