/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication7;

/**
 *
 * @author vishn
 */
import java.sql.*;
public class ureg extends javax.swing.JFrame {

    /**
     * Creates new form ureg
     */
    Connection con;
    PreparedStatement pr;
    public ureg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        na = new javax.swing.JTextField();
        us = new javax.swing.JTextField();
        ps = new javax.swing.JTextField();
        jo = new javax.swing.JTextField();
        n = new javax.swing.JTextField();
        ad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        jTextField7.setText("jTextField7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        na.setBackground(new java.awt.Color(0, 0, 0));
        na.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        na.setForeground(new java.awt.Color(0, 204, 204));
        na.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(na, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 180, 40));

        us.setBackground(new java.awt.Color(0, 0, 0));
        us.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        us.setForeground(new java.awt.Color(0, 204, 204));
        us.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(us, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 180, 40));

        ps.setBackground(new java.awt.Color(0, 0, 0));
        ps.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        ps.setForeground(new java.awt.Color(0, 204, 204));
        ps.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        ps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psActionPerformed(evt);
            }
        });
        getContentPane().add(ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 180, 40));

        jo.setBackground(new java.awt.Color(0, 0, 0));
        jo.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jo.setForeground(new java.awt.Color(0, 204, 204));
        jo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(jo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 180, 40));

        n.setBackground(new java.awt.Color(0, 0, 0));
        n.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        n.setForeground(new java.awt.Color(0, 204, 204));
        n.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 180, 40));

        ad.setBackground(new java.awt.Color(0, 0, 0));
        ad.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        ad.setForeground(new java.awt.Color(0, 204, 204));
        ad.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 180, 80));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 204));
        jButton1.setText("REGISTER");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 140, 50));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("JOB                      :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("MOBILE NUMBER       :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 130, 40));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("ADDRESS             :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 140, 40));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText(" NAME                     :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 230, 20));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 204));
        jLabel7.setText(" PASSWORD               :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 230, 40));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 204));
        jLabel9.setText("  USERNAME               :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 230, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/big_thumb_73a360c68042ae98f65d8a49936ea78c.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 720, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void psActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name=na.getText();
        String usn=us.getText();
        String pw=ps.getText();
        String job=jo.getText();
        int no=Integer.parseInt(n.getText());
        String addr=ad.getText();
        try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        String server="localhost";
        String portnumber="1521";
        String sid="xe";
        String url="jdbc:oracle:thin:@"+server+":"+portnumber+":"+sid;
        con=DriverManager.getConnection(url,"system","9961");
        pr=con.prepareStatement("insert into user1 values(?,?,?,?,?,?)");
        pr.setString(1,name);
        pr.setString(2,job);
        pr.setString(3,usn);
        pr.setString(4,pw);
        pr.setInt(5,no);
        pr.setString(6,addr);
        pr.executeUpdate();
        hide();
        String a[]={usn,pw}; con.close();
        user.main(a);
    }//GEN-LAST:event_jButton1ActionPerformed
    catch(ClassNotFoundException e){
        System.out.println("error1");
    }
    catch(SQLException e){
    System.out.println("error2");
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ureg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ureg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ureg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ureg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ureg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jo;
    private javax.swing.JTextField n;
    private javax.swing.JTextField na;
    private javax.swing.JTextField ps;
    private javax.swing.JTextField us;
    // End of variables declaration//GEN-END:variables
}
