/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication7;

/**
 *
 * @author vishn
 */
import java.sql.*;

public class user extends javax.swing.JFrame {

    /**
     * Creates new form user
     */
    static String usn;
    
    String u;
    public user() {
        initComponents();
    }
public void connect()
{
    
            
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        co = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        ti = new javax.swing.JTextField();
        da = new javax.swing.JTextField();
        st = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fi = new javax.swing.JTextField();
        ow = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ca = new javax.swing.JTextField();
        mo = new javax.swing.JTextField();
        no = new javax.swing.JTextField();
        msg = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(81, 194, 167));
        jLabel1.setText("     OWNER                          CAR NO                                PHONE NUMBER                              COST");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 600, -1));

        co.setEditable(false);
        co.setBackground(new java.awt.Color(0, 0, 0));
        co.setForeground(new java.awt.Color(0, 204, 204));
        co.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(co, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 105, 32));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(81, 194, 167));
        jButton2.setText("TAKE IT !!");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 144, 43));

        ti.setEditable(false);
        ti.setBackground(new java.awt.Color(0, 0, 0));
        ti.setForeground(new java.awt.Color(0, 204, 204));
        ti.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(ti, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 100, 40));

        da.setEditable(false);
        da.setBackground(new java.awt.Color(0, 0, 0));
        da.setForeground(new java.awt.Color(0, 204, 204));
        da.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(da, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 91, 40));

        st.setBackground(new java.awt.Color(0, 0, 0));
        st.setForeground(new java.awt.Color(0, 204, 204));
        st.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 138, 40));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(81, 194, 167));
        jLabel2.setText("         DATE                                           TIME                                   NO. OF PASSENGERS ALLOWED");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 570, -1));

        fi.setBackground(new java.awt.Color(0, 0, 0));
        fi.setForeground(new java.awt.Color(0, 204, 204));
        fi.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(fi, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 137, 40));

        ow.setEditable(false);
        ow.setBackground(new java.awt.Color(0, 0, 0));
        ow.setForeground(new java.awt.Color(0, 204, 204));
        ow.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(ow, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, 32));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(81, 194, 167));
        jButton1.setText("GO");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 50, -1));

        ca.setEditable(false);
        ca.setBackground(new java.awt.Color(0, 0, 0));
        ca.setForeground(new java.awt.Color(0, 204, 204));
        ca.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        ca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caActionPerformed(evt);
            }
        });
        getContentPane().add(ca, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 150, 32));

        mo.setEditable(false);
        mo.setBackground(new java.awt.Color(0, 0, 0));
        mo.setForeground(new java.awt.Color(0, 204, 204));
        mo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(mo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 160, 32));

        no.setEditable(false);
        no.setBackground(new java.awt.Color(0, 0, 0));
        no.setForeground(new java.awt.Color(0, 204, 204));
        no.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 100, 40));

        msg.setEditable(false);
        msg.setBackground(new java.awt.Color(0, 0, 0));
        msg.setForeground(new java.awt.Color(255, 255, 255));
        msg.setBorder(null);
        msg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgActionPerformed(evt);
            }
        });
        getContentPane().add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 640, 20));

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(81, 194, 167));
        jButton3.setText("VIEW CURRENT RIDE DETAILS");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 290, 40));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(81, 194, 167));
        jLabel3.setText("    STARTING POINT                         FINISHING POINT");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 290, -1));

        jLabel4.setBackground(new java.awt.Color(0, 204, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/user2.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        msg.setText("");
        
    try{
        Connection con;
    PreparedStatement pr;
    String day,time,owner,mobile,car,pw;
    int cost;
    
    ResultSet rs;
        Class.forName("oracle.jdbc.driver.OracleDriver");
        String server="localhost";
        String portnumber="1521";
        String sid="xe";
        int flag=0;
        String url="jdbc:oracle:thin:@"+server+":"+portnumber+":"+sid;
        con=DriverManager.getConnection(url,"system","9961");
        String s=st.getText();
        String p=fi.getText();
        pr=con.prepareStatement("select * from ride where start1=? and finish=? and usn not in(select osn from pool)");
        pr.setString(1,s);
        pr.setString(2,p);
        rs=pr.executeQuery();
        while(rs.next())
        {
            da.setText(rs.getString("day"));
            ti.setText(rs.getString("time"));
            co.setText(Integer.toString(rs.getInt("cost")));
            no.setText(Integer.toString(rs.getInt("no")));
            Statement st=con.createStatement();
            u=rs.getString("usn");
            flag=1;
        ResultSet rq=st.executeQuery("select * from owner where usn='"+u+"'");
        while(rq.next())
                {
                    ow.setText(rq.getString("name"));
                    ca.setText(rq.getString("car"));
                    mo.setText(Integer.toString(rq.getInt("no")));
                }
        }
        if(flag==1){
            msg.setText("NO AVAILABLE RIDES");
            con.close();
        }
    }  
    catch(ClassNotFoundException e){
        System.out.println(e+"3");
    }
    catch(SQLException e){
    System.out.println(e+"4");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            Connection con;
    PreparedStatement pr;
    String day,time,owner,mobile,car,pw;
    int cost;
    
    ResultSet rs;
            Class.forName("oracle.jdbc.driver.OracleDriver");
        String server="localhost";
        String portnumber="1521";
        String sid="xe";
        String url="jdbc:oracle:thin:@"+server+":"+portnumber+":"+sid;
        con=DriverManager.getConnection(url,"system","9961");
        pr=con.prepareStatement("insert into pool values(?,?)");
        pr.setString(1,usn);
        pr.setString(2,u);
        pr.executeUpdate();
        }
        catch(ClassNotFoundException e)
        {
            System.out.println(e+"5");
        }
        catch(SQLException e){
            msg.setText("YOU HAVE ALREADY TAKEN A RIDE ONLY ONE RIDE CAN BE TAKEN AT A TIME");
        System.out.println(e+"6");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void msgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msgActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try
    {
        Connection con;
    PreparedStatement pr;
    String day,time,owner,mobile,car,pw;
    int cost;
    
    ResultSet rs;
        Class.forName("oracle.jdbc.driver.OracleDriver");
        String server="localhost";
        String portnumber="1521";
        String sid="xe";
        String url="jdbc:oracle:thin:@"+server+":"+portnumber+":"+sid;
        con=DriverManager.getConnection(url,"system","9961");
        pr=con.prepareStatement("select * from pool where usn=?");
        pr.setString(1,usn);
        rs=pr.executeQuery();
        String a[]={usn};
        while(rs.next()){con.close();
            rideuser.main(a);}
        con.close();
    }
    catch(ClassNotFoundException e){
        System.out.println(e+"1");
    }
    catch(SQLException e){
    System.out.println(e+"2");
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        usn=args[0];
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        usn=args[0];

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ca;
    private javax.swing.JTextField co;
    private javax.swing.JTextField da;
    private javax.swing.JTextField fi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField mo;
    private javax.swing.JTextField msg;
    private javax.swing.JTextField no;
    private javax.swing.JTextField ow;
    private javax.swing.JTextField st;
    private javax.swing.JTextField ti;
    // End of variables declaration//GEN-END:variables
}
